name: repoBworkflow
on:
  repository_dispatch:
    types: [RepoAevent]
  push:

jobs:
  repoBjobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: testB
        run: |
          echo event triggered.
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          RUN_NUMBER: ${{ github.run_number }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$RUN_NUMBER"
          expr $RUN_NUMBER - 1
